// ===== Suspect Records Database =====
const SUSPECTS = [
  {
    code: "BW-S-0041",
    name: "Marcus Delgado",
    alias: "The Courier",
    dob: "1984-06-12",
    gender: "Male",
    height: "6'1\"",
    weight: "195 lbs",
    lastLocation: "Dockside Warehouse District",
    address: "Unknown — last seen near 44 Harbor Row",
    threatLevel: "critical",
    status: "wanted",
    caseNum: "BW-2026-0882",
    officer: "Det. J. Ford",
    dateEntered: "2026-01-14",
    associates: "Elena Voss, Raymond \"Ghost\" Tanner, Unknown associate (codename: Sparrow)",
    history: "Three prior arrests: aggravated assault (2018, convicted), possession with intent (2020, plea deal), weapons trafficking (2024, acquitted on technicality). Known enforcer for Blackwater dockside operations. Suspected involvement in the disappearance of witness Carl Rayburn.",
    notes: "Delgado was identified through CCTV footage near the Harbor Row storage units on Jan 12. Witness testimony places him at the scene of the Rayburn disappearance. Considered armed and extremely dangerous. Do not approach without backup. Warrant issued Jan 14 — Judge Morrison, 7th Circuit."
  },
  {
    code: "BW-S-0042",
    name: "Elena Voss",
    alias: "Red",
    dob: "1991-03-28",
    gender: "Female",
    height: "5'7\"",
    weight: "138 lbs",
    lastLocation: "Greystone Apartments, Unit 12B",
    address: "88 Greystone Apartments, Apt 12B",
    threatLevel: "high",
    status: "under-investigation",
    caseNum: "BW-2026-0883",
    officer: "Det. R. Jackson",
    dateEntered: "2026-01-16",
    associates: "Marcus Delgado, Victor Kaine, Lana Moretti",
    history: "One prior arrest: fraud and identity theft (2021, 18 months served). Financial records show shell companies linked to money laundering. Known to use multiple aliases and forged identification.",
    notes: "Voss is believed to be the financial coordinator for Delgado's network. Bank records subpoenaed on Jan 15 revealed wire transfers to offshore accounts totaling over $2.3M. Currently under 24-hour surveillance. Cooperating witnesses suggest she may be willing to negotiate — approach with caution through legal counsel."
  },
  {
    code: "BW-S-0043",
    name: "Raymond Tanner",
    alias: "Ghost",
    dob: "1979-11-05",
    gender: "Male",
    height: "5'10\"",
    weight: "172 lbs",
    lastLocation: "Last pinged — Blackwater Rail Yard",
    address: "No fixed address — previously 19 Coal St.",
    threatLevel: "high",
    status: "wanted",
    caseNum: "BW-2026-0884",
    officer: "Det. J. Ford",
    dateEntered: "2026-01-18",
    associates: "Marcus Delgado, unknown female (mid-30s, dark hair)",
    history: "Extensive record: B&E (2005), armed robbery (2008, 5 years served), assault on a police officer (2015, 3 years served), evading arrest (2022). Known to operate under false identities. Has evaded two previous warrants.",
    notes: "Tanner's cell phone last pinged near the rail yard on Jan 17 before going dark. Informant suggests he may have fled to the county line. Interstate APB filed. Fingerprints recovered from the Rayburn residence match Tanner. Field teams should treat as high-risk — history of violence against law enforcement."
  },
  {
    code: "BW-S-0044",
    name: "Victor Kaine",
    alias: "V.K.",
    dob: "1975-08-22",
    gender: "Male",
    height: "6'3\"",
    weight: "225 lbs",
    lastLocation: "Kaine Holdings Office, 3rd & Main",
    address: "1200 Ridgemont Drive, Blackwater Hills",
    threatLevel: "medium",
    status: "under-investigation",
    caseNum: "BW-2026-0901",
    officer: "Det. M. Valdez",
    dateEntered: "2026-01-22",
    associates: "Elena Voss, City Councilman Parks (unconfirmed), various business associates",
    history: "No prior criminal record. Owner of Kaine Holdings — real estate and development. Multiple civil suits filed against him (harassment, breach of contract — all settled). IRS audit flagged in 2024, no charges filed.",
    notes: "Kaine surfaced during the Voss financial investigation. Wire transfers from Voss shell companies routed through Kaine Holdings accounts. Investigation suggests Kaine may be laundering funds through property deals. Politically connected — proceed carefully. All subpoenas require DA approval."
  },
  {
    code: "BW-S-0045",
    name: "Lana Moretti",
    alias: "None on file",
    dob: "1988-12-03",
    gender: "Female",
    height: "5'5\"",
    weight: "125 lbs",
    lastLocation: "Moretti's Bar & Lounge, Wharf St.",
    address: "Moretti's Bar & Lounge, 77 Wharf St.",
    threatLevel: "low",
    status: "cleared",
    caseNum: "BW-2026-0902",
    officer: "Off. R. Jackson",
    dateEntered: "2026-01-25",
    associates: "Elena Voss (college acquaintance)",
    history: "No criminal record. Owns Moretti's Bar & Lounge, licensed since 2019. Questioned as part of the Voss investigation.",
    notes: "Moretti was initially flagged when surveillance showed Voss frequenting her establishment. Interview conducted Jan 24 — Moretti stated she hadn't spoken to Voss in over a year and was unaware of any illegal activity. Phone records and financial review corroborate her account. Cleared of involvement. Case note: remove from active watch list."
  },
  {
    code: "BW-S-0046",
    name: "Derek \"Slim\" Hawkins",
    alias: "Slim",
    dob: "1993-04-17",
    gender: "Male",
    height: "6'0\"",
    weight: "155 lbs",
    lastLocation: "Blackwater County Jail — Block C",
    address: "N/A — In custody",
    threatLevel: "medium",
    status: "in-custody",
    caseNum: "BW-2026-0910",
    officer: "Off. J. Ford",
    dateEntered: "2026-02-01",
    associates: "Marcus Delgado, Raymond Tanner, street-level dealers (names redacted)",
    history: "Arrests: possession (2016), possession with intent (2018, 2 years served), distribution (2023, probation). Known street-level operator. Picked up on Feb 1 during a routine traffic stop — outstanding warrant for probation violation.",
    notes: "Hawkins was arrested on Feb 1 after a traffic stop on Industrial Ave revealed an outstanding warrant. During processing, Hawkins offered information on Delgado's operations in exchange for consideration. Currently awaiting interview with DA's office. Placed in protective custody per request — claims fear of retaliation."
  },
  {
    code: "BW-S-0047",
    name: "Nina Castellano",
    alias: "The Accountant",
    dob: "1986-09-14",
    gender: "Female",
    height: "5'6\"",
    weight: "140 lbs",
    lastLocation: "Castellano CPA Office, Elm St.",
    address: "340 Elm Street, Suite 4A",
    threatLevel: "medium",
    status: "under-investigation",
    caseNum: "BW-2026-0920",
    officer: "Det. M. Valdez",
    dateEntered: "2026-02-08",
    associates: "Victor Kaine (client relationship), Elena Voss (suspected)",
    history: "No criminal record. CPA license issued 2012. Previously employed at Morrison & Associates before opening private practice in 2018. Flagged by forensic accounting unit during the Kaine Holdings review.",
    notes: "Castellano's firm handled bookkeeping for three of the shell companies linked to the Voss-Kaine money trail. Forensic review of her files shows discrepancies that suggest knowing participation, though her attorney argues she was unaware of the source of funds. Subpoena served Feb 7 for all Kaine Holdings records. Interview scheduled."
  },
  {
    code: "BW-S-0048",
    name: "Tommy Briggs",
    alias: "Torch",
    dob: "1990-07-30",
    gender: "Male",
    height: "5'9\"",
    weight: "180 lbs",
    lastLocation: "Blackwater County Jail — Block A",
    address: "N/A — In custody",
    threatLevel: "high",
    status: "in-custody",
    caseNum: "BW-2025-0744",
    officer: "Det. J. Ford",
    dateEntered: "2025-11-20",
    associates: "Unknown — operates independently",
    history: "Arson (2015, 4 years served), arson causing bodily harm (2021, charges reduced — 2 years served). Three confirmed arsons in the Blackwater industrial corridor between Sept-Nov 2025. Arrested Nov 19 after being caught on private security cameras at the Millfield Paper Co. warehouse.",
    notes: "Briggs confessed to two of the three industrial corridor fires during interrogation. Denies involvement in the third (Greystone Storage, Oct 3) despite physical evidence placing him at the scene. Awaiting trial — bail denied due to flight risk assessment. Psychiatric evaluation recommended by defense counsel."
  },
  {
    code: "BW-S-0049",
    name: "James Whitfield",
    alias: "None on file",
    dob: "1968-02-19",
    gender: "Male",
    height: "5'11\"",
    weight: "200 lbs",
    lastLocation: "Whitfield residence, 88 Oak Lane",
    address: "88 Oak Lane, Blackwater Heights",
    threatLevel: "low",
    status: "released",
    caseNum: "BW-2026-0855",
    officer: "Off. M. Valdez",
    dateEntered: "2025-12-15",
    associates: "None known",
    history: "No prior criminal record. Retired school principal. Arrested Dec 14 following a domestic disturbance call — charges filed by spouse, later withdrawn.",
    notes: "Whitfield was arrested after neighbors reported a loud altercation at 88 Oak Lane. Responding officers found signs of property damage but no physical injuries. Spouse filed charges but withdrew them Dec 20, stating the situation was a one-time escalation. Released on own recognizance. Mandatory anger management counseling ordered. Follow-up visit conducted Jan 5 — no further incidents."
  },
  {
    code: "BW-S-0050",
    name: "Sasha Petrov",
    alias: "The Broker",
    dob: "1982-01-07",
    gender: "Female",
    height: "5'8\"",
    weight: "145 lbs",
    lastLocation: "Unknown — last seen Blackwater Int'l Airport",
    address: "Previously: 500 Marina Tower, Penthouse B",
    threatLevel: "critical",
    status: "wanted",
    caseNum: "BW-2026-0950",
    officer: "Det. R. Jackson",
    dateEntered: "2026-02-20",
    associates: "International contacts (names classified — see FBI liaison file), Victor Kaine, Marcus Delgado",
    history: "Interpol Red Notice issued 2023 (wire fraud, conspiracy). No prior US arrests. Entered the country on a forged passport in 2024. Believed to be the connecting point between local operations and international buyers.",
    notes: "Petrov was identified through intercepted communications between Kaine and an encrypted phone registered to a Marina Tower address. FBI liaison confirmed Interpol's interest. Airport CCTV captured Petrov passing through departures on Feb 18 — flight manifest shows a ticket to Montreal. Canadian authorities notified. If located, do not attempt solo apprehension — contact FBI field office immediately."
  },
  {
    code: "BW-S-0051",
    name: "Carlos Ruiz",
    alias: "El Lobo",
    dob: "1987-05-23",
    gender: "Male",
    height: "5'8\"",
    weight: "170 lbs",
    lastLocation: "Blackwater County Jail — Block B",
    address: "N/A — In custody",
    threatLevel: "high",
    status: "in-custody",
    caseNum: "BW-2026-0935",
    officer: "Off. J. Ford",
    dateEntered: "2026-02-12",
    associates: "Marcus Delgado, Derek Hawkins, street-level network",
    history: "Arrests: assault (2012), distribution of controlled substances (2015, 3 years served), possession of unregistered firearm (2021, probation). Picked up during a coordinated raid on Feb 11 at a stash house on Industrial Ave.",
    notes: "Ruiz was arrested during a multi-unit raid targeting Delgado's distribution network. Officers recovered 4 kg of narcotics and $85,000 in cash. Ruiz has not cooperated with investigators. Bail set at $500,000 — not posted. Trial date pending. Co-defendants include two unidentified males (processing ongoing)."
  },
  {
    code: "BW-S-0052",
    name: "Diane Marchetti",
    alias: "None on file",
    dob: "1976-10-11",
    gender: "Female",
    height: "5'4\"",
    weight: "130 lbs",
    lastLocation: "Marchetti residence, 22 Cedar Ct.",
    address: "22 Cedar Court, Blackwater",
    threatLevel: "low",
    status: "released",
    caseNum: "BW-2026-0860",
    officer: "Off. R. Jackson",
    dateEntered: "2025-12-28",
    associates: "None known",
    history: "One prior: shoplifting (2019, fine paid). Arrested Dec 27 for DUI on River Bridge.",
    notes: "Marchetti was stopped at a DUI checkpoint on River Bridge after failing a field sobriety test. BAC registered 0.14. No accident or injuries. Released next morning on bail. Pled guilty — license suspended 6 months, mandatory DUI education program. Compliant with all court orders as of last check."
  }
];

// ===== Authorized Users =====
const AUTH_USERS = {
  '2323': { password: 'ford', name: 'J. Ford', badge: '2323', rank: 'Detective' },
  '7203': { password: 'jackson', name: 'R. Jackson', badge: '7203', rank: 'Detective' },
  '1738': { password: 'valdez', name: 'M. Valdez', badge: '1738', rank: 'Detective' }
};
